import { AuthProvider } from "@/components/Auth/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { DefaultHeader } from "@/components/DefaultHeader";
import { DefaultFooter } from "@/components/DefaultFooter";
import { Providers } from "@/components/Redux/Provider";
import { DefaultSidebar } from "@/components/DefaultSidebar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Đồ Án Tốt Nghiệp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <ToastContainer theme="dark"></ToastContainer>
          <Providers>
            <DefaultSidebar>
              <div className="">
                {children}
                {/* <DefaultFooter></DefaultFooter> */}
              </div>
            </DefaultSidebar>
          </Providers>
        </body>
      </html>
    </AuthProvider>
  );
}
