import { AuthProvider } from "@/components/Auth/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { DefaultHeader } from "@/components/DefaultHeader";
import { DefaultFooter } from "@/components/DefaultFooter";
import { Providers } from "@/components/Redux/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <Providers>
            <DefaultHeader></DefaultHeader>
            <div className="">
              {children}
              <DefaultFooter></DefaultFooter>
            </div>
          </Providers>
        </body>
      </html>
    </AuthProvider>
  );
}
